### PR TITLE
switch to 1k instead of 100k

### PR DESCRIPTION
**Pull request by benubah**
This PR tries to switch from 100k to 1k metric based on the last task in the issue here: https://github.com/dsbbfinddx/shinyfindapps/issues/55

Does this work?

### CODE REVIEW

**Review by christophsax — COMMENTED** [review]
I don't like having the wrong name here. Perhaps we add a new column `pop` and stop using `pop_100k` in later apps?

**Comment by christophsax** [comment]
Will give it a try

**Comment by christophsax** [comment]
@angelicambg Does it look ok to you?

**Review by christophsax — APPROVED** [review]

**Comment by angelicambg** [comment]
Looks good to me and it's better to have both variables with the proper names to avoid confusion

**Comment by benubah** [comment]
> 
> 
> Looks good to me and it's better to have both variables with the proper names to avoid confusion

You mean `pop_100k` and `pop_1k` or  `pop`?  What exactly should we enter into [codebook.csv](https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/codebook.csv) following this change?

**Comment by christophsax** [comment]
We have now `pop` in `get_data_all()$data_all`. This should be used. `pop_100k` should be removed once the old app is decommissioned.

Codebook should be updated to include `pop`.

**Pull request merged**
